apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: hunt-ui
  name: pod-hunt-src
  namespace: pod-hunt
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: hunt-ui:src
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/vrutkovs/DuckHunt-JS
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: "hunt-ui:nodejs0.10"
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 7b6c52a8146202e3
    type: GitHub
  - type: ImageChange
  - type: ConfigChange
