kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-hunt-ripper-cluster-admin
subjects:
  - kind: ServiceAccount
    name: ripper
    namespace: pod-hunt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
