kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-admin
  namespace: pod-hunt
subjects:
  - kind: ServiceAccount
    name: default
    namespace: pod-hunt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
